# Generated by Django 6.0.3 on 2026-03-30 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم العلمي')),
                ('therapeutic_category', models.CharField(choices=[('antibiotic', 'مضاد حيوي'), ('analgesic', 'مسكن'), ('antihypertensive', 'خافض ضغط'), ('antidiabetic', 'علاج السكري'), ('cardiovascular', 'قلبي وعائي'), ('other', 'أخرى')], max_length=50)),
                ('common_dosages', models.JSONField(default=list, help_text='قائمة بالجرعات الشائعة')),
                ('common_side_effects', models.TextField(blank=True, verbose_name='الآثار الجانبية الشائعة')),
                ('warnings', models.TextField(blank=True, verbose_name='التحذيرات')),
                ('interactions', models.TextField(blank=True, verbose_name='التفاعلات الدوائية')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='معدل النجاح %')),
                ('side_effect_rate', models.FloatField(default=0.0, verbose_name='معدل الآثار الجانبية %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دواء في المكتبة',
                'verbose_name_plural': 'مكتبة الأدوية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('dosage', models.CharField(max_length=100, verbose_name='الجرعة')),
                ('frequency', models.IntegerField(default=1, verbose_name='عدد المرات يومياً')),
                ('relation_to_meal', models.CharField(choices=[('before_meal', 'قبل الأكل'), ('after_meal', 'بعد الأكل'), ('with_meal', 'مع الأكل'), ('empty_stomach', 'على معدة فارغة')], default='after_meal', max_length=50)),
                ('importance_level', models.IntegerField(choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'مرتفع'), (4, 'عالي'), (5, 'حرج')], default=3)),
                ('is_critical', models.BooleanField(default=False, verbose_name='دواء حرج')),
                ('current_stock', models.IntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('min_stock_threshold', models.IntegerField(default=5, verbose_name='حد التنبيه')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات خاصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_from_library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.druglibrary', verbose_name='الدواء من المكتبة')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دواء المريض',
                'verbose_name_plural': 'أدوية المرضى',
                'ordering': ['-importance_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='التاريخ')),
                ('scheduled_time', models.TimeField(verbose_name='الوقت')),
                ('calculated_dose', models.CharField(max_length=100, verbose_name='الجرعة المحسوبة')),
                ('meal_relation', models.CharField(max_length=50, verbose_name='العلاقة بالوجبة')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('taken', 'مأخوذة'), ('missed', 'فاتت'), ('postponed', 'مؤجلة'), ('skipped', 'متخطاة')], default='pending', max_length=20)),
                ('taken', models.BooleanField(default=False, verbose_name='تم الأخذ')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الأخذ الفعلي')),
                ('is_delayed', models.BooleanField(default=False, verbose_name='متأخرة')),
                ('delay_minutes', models.IntegerField(default=0, verbose_name='دقائق التأخير')),
                ('is_critical', models.BooleanField(default=False, verbose_name='حرجة')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='تم إرسال التذكير')),
                ('reminder_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت التذكير')),
                ('doctor_decision', models.CharField(blank=True, choices=[('double_next', 'مضاعفة الجرعة القادمة'), ('skip', 'تخطي الجرعة'), ('take_later', 'أخذها لاحقاً'), ('reschedule', 'إعادة جدولتها')], max_length=20, null=True)),
                ('doctor_decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.patientmedication')),
            ],
            options={
                'verbose_name': 'جدول جرعة',
                'verbose_name_plural': 'الجدول الذكي',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('medication', 'تقرير دواء'), ('adherence', 'تقرير التزام')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_doses', models.IntegerField(default=0, verbose_name='إجمالي الجرعات')),
                ('taken_doses', models.IntegerField(default=0, verbose_name='الجرعات المأخوذة')),
                ('missed_doses', models.IntegerField(default=0, verbose_name='الجرعات الفائتة')),
                ('critical_missed', models.IntegerField(default=0, verbose_name='الجرعات الحرجة الفائتة')),
                ('adherence_rate', models.FloatField(default=0.0, verbose_name='نسبة الالتزام %')),
                ('detailed_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات تفصيلية')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('is_generated', models.BooleanField(default=False, verbose_name='تم إنشاؤه')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_effect', models.CharField(max_length=200, verbose_name='الأثر الجانبي')),
                ('severity', models.CharField(choices=[('mild', 'خفيف'), ('moderate', 'متوسط'), ('severe', 'شديد')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='وصف إضافي')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('alternative_suggested', models.BooleanField(default=False, verbose_name='تم اقتراح بديل')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effects', to='medications.patientmedication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_side_effects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'أثر جانبي',
                'verbose_name_plural': 'الآثار الجانبية',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('medication_reminder', 'تذكير دواء'), ('critical_alert', 'تنبيه حرج'), ('stock_alert', 'تنبيه نفاذ'), ('expiry_alert', 'تنبيه انتهاء صلاحية'), ('doctor_decision', 'قرار طبي'), ('report_ready', 'تقرير جاهز'), ('side_effect', 'تأثير جانبي')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('in_app', 'داخل التطبيق'), ('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('read', 'مقروء'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(verbose_name='مجدول لـ')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medicationschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['user', 'status'], name='medications_user_id_190c50_idx'), models.Index(fields=['scheduled_for'], name='medications_schedul_453a53_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='medications_schedul_a5af9e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['patient', 'status'], name='medications_patient_389dbe_idx'),
        ),
    ]
