# Generated by Django 6.0.4 on 2026-05-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='medications_user_id_190c50_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='medications_schedul_453a53_idx',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
