# Generated by Django 6.0.3 on 2026-03-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('patient', 'مريض'), ('doctor', 'طبيب'), ('supervisor', 'مشرف')], default='patient', max_length=20),
        ),
    ]
