# Generated by Django 6.0.4 on 2026-05-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تم الموافقة عليه'),
        ),
        migrations.AddField(
            model_name='users',
            name='license_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط صورة الشهادة'),
        ),
    ]
