# Generated by Django 6.0.4 on 2026-05-19 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_doses', models.IntegerField(default=0, verbose_name='إجمالي الجرعات')),
                ('taken_doses', models.IntegerField(default=0, verbose_name='الجرعات المأخوذة')),
                ('missed_doses', models.IntegerField(default=0, verbose_name='الجرعات الفائتة')),
                ('critical_missed', models.IntegerField(default=0, verbose_name='الجرعات الحرجة الفائتة')),
                ('adherence_rate', models.FloatField(default=0.0, verbose_name='نسبة الالتزام %')),
                ('detailed_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات تفصيلية')),
                ('is_generated', models.BooleanField(default=False, verbose_name='تم إنشاؤه')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-period_end'],
                'unique_together': {('patient', 'report_type', 'period_start', 'period_end')},
            },
        ),
    ]
