# Generated by Django 6.0.4 on 2026-05-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('medication_reminder', 'تذكير دواء'), ('critical_alert', 'تنبيه حرج'), ('stock_alert', 'تنبيه نفاذ'), ('expiry_alert', 'تنبيه انتهاء صلاحية'), ('doctor_decision', 'قرار طبي'), ('report_ready', 'تقرير جاهز'), ('side_effect', 'تأثير جانبي')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('in_app', 'داخل التطبيق'), ('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('sent', 'مرسل'), ('delivered', 'تم التسليم'), ('read', 'مقروء'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('user_action', models.CharField(blank=True, choices=[('taken', 'تم أخذ الجرعة'), ('postponed', 'تم تأجيل الجرعة'), ('snooze', 'تم تأجيل الإشعار'), ('dismissed', 'تم تجاهل الإشعار')], max_length=20, null=True)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
